### ISSUE TITLE
Automatically load use organizations

### ISSUE THREAD

**Issue by splintor** [oriprice/eyfo#14]
You can use https://github.com/settings/organizations to load the organizations that the current user belongs to and add them to the list of organizations.

**Comment by oriprice** [comment]
nice i'll check that out

**Comment by oriprice** [comment]
Resolved in ver 1.0.5

**Comment by splintor** [comment]
This was resolved in `1.0.4`...

Thanks!

**Comment by oriprice** [comment]
1.0.4 had a major bug. 
Please use at least 1.0.5.
