### ISSUE TITLE
Search link not working

### ISSUE THREAD

**Issue by mastertheblaster** [oriprice/eyfo#8]
When i click on `Google Search Algorithm` nothing happens

![screenshot 2019-01-11 at 09 53 37](https://user-images.githubusercontent.com/10008149/51020314-dd0e1780-1586-11e9-9646-166c41471a01.png)

**Comment by oriprice** [comment]
Well, that link was meant to be a joke.. (obviously not a good one...:))

**Comment by oriprice** [comment]
Done.
